name: Deploy to testpypi for develop branch

on:
  pull_request:
    branches:
      - develop

jobs:
  run_tests_for_local_Sanga_package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install basic dependencies
        run: pip install flake8 pytest pytest-cov pytest-mock

      - uses: actions/cache@v2
        id: cache_pip
        with:
          path: ${{ env.pythonLocation }}/lib/python${{ matrix.python-version }}/site-packages/*
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies (requirements.txt) if no cache_pip
        if: steps.cache_pip.outputs.cache-hit != 'true'
        run: |
          if [ -f requirements.txt ]; then
              pip install -r requirements.txt
          else
              echo "requirements.txt not found !" 
          fi

      - name: Lint with flake8
        run: flake8 .

      - name: Test tests/media/* with pytest
        run: PYTHONPATH=./::./src pytest tests/ --log-cli-level=warning --cov=./ --cov-report=term-missing

  upload_Sanga_package_to_testpypi:
    needs: run_tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install basic dependencies
        run: pip install --upgrade build twine

      - name: build and upload to testpypi
        env:
          TWINE_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
        run: |
          python3 -m build
          python3 -m twine upload -r testpypi dist/*
